import Link from "next/link";
import type { Metadata } from "next";
import { loadAnalysis } from "@/lib/store";
import { ContextMapView } from "@/components/ContextMapView";
import { GeneratedOutput } from "@/components/GeneratedOutput";

export const runtime = "nodejs";

interface Params {
  params: Promise<{ owner: string; repo: string }>;
}

export async function generateMetadata({ params }: Params): Promise<Metadata> {
  const { owner, repo } = await params;
  return {
    title: `${owner}/${repo} — SigMap context map`,
    description: `Verified SigMap signature context for ${owner}/${repo}.`,
  };
}

export default async function PermalinkPage({ params }: Params) {
  const { owner, repo } = await params;
  const map = await loadAnalysis(`${owner}/${repo}`);

  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <header className="mb-8 flex items-center justify-between gap-4">
        <h1 className="text-2xl font-bold tracking-tight">
          {owner}/{repo}
        </h1>
        <Link
          href="/demo"
          className="shrink-0 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-blue-500"
        >
          Try your own repo →
        </Link>
      </header>

      {map ? (
        <div className="space-y-6">
          <ContextMapView map={map} />
          <GeneratedOutput map={map} />
        </div>
      ) : (
        <div className="rounded-lg border border-zinc-200 p-6 text-sm text-zinc-600 dark:border-zinc-800 dark:text-zinc-400">
          No saved analysis for{" "}
          <code>
            {owner}/{repo}
          </code>{" "}
          yet.{" "}
          <Link
            href="/demo"
            className="text-blue-600 hover:underline dark:text-blue-400"
          >
            Analyze it on the demo
          </Link>
          .
        </div>
      )}

      <footer className="mt-16 border-t border-zinc-200 pt-6 text-sm text-zinc-500 dark:border-zinc-800">
        Generated by SigMap ·{" "}
        <a
          href="https://sigmap.io"
          className="text-blue-600 hover:underline dark:text-blue-400"
        >
          sigmap.io
        </a>
      </footer>
    </main>
  );
}
